route:
  receiver: 'pushover'

receivers:
  - name: 'pushover'
    pushover_configs:
      - url: 'https://api.pushover.net/1/messages.json'
        token: 'YOUR_PUSHOVER_APP_TOKEN'
        user: 'YOUR_PUSHOVER_USER_KEY'
        priority: 0
        retry: 1m
        expire: 1h


